image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
    - scalameta.metals@1.9.0:KNju0fLBpNiyqH8qBfFeIQ==
ports:
  - port: 8212
    onOpen: ignore